### ISSUE TITLE
How disable a test?

### ISSUE THREAD

**Issue by thiaguerd** [lucascaton/massa#9]
I see that a only way to disable a check is remove  all info of check on massa.yml

What you think about we use a attr to set if check is enabled? 

Something Like

```yml
rubocop:
  enabled:     false
  description: 'Rubocop'
  command:     'bundle exec rubocop'
  required:    true
```
